[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://ametojsingh.netlify.app/"
  to = "https://singamet.netlify.app/:splat"
  status = 301
  force = true
